// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sphere/errors/errors.proto

// buf:lint:ignore PACKAGE_VERSION_SUFFIX

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error defines error metadata for an enum value, specifying its HTTP status code,
// reason identifier, and user-facing error message.
//
// Preconditions: status must be a valid HTTP status code (100-599). When status is 0,
// code generators fall back to default_status, or 500 if default_status is unset.
// Concurrency: Protobuf messages are not safe for concurrent mutation. Read-only access is safe.
// Lifecycle: Instances returned by proto.GetExtension are shared descriptor values; do not mutate in-place.
// Error semantics: Enum value 0 (<ENUM>_UNSPECIFIED) is reserved as non-error; returning it defaults to 500 Unknown.
// Side-effects: Pure data definition; no background tasks or context manipulation.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the HTTP status code (e.g. 400, 404, 500). If 0, code generators fall back
	// to the enclosing enum's default_status (or 500 if unset). Valid range is 100-599.
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// reason is a machine-readable error code or reason string (e.g. "USER_NOT_FOUND").
	// If empty, code generators derive it from the enum and value name.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// message is a human-readable, user-facing error message.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_sphere_errors_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_sphere_errors_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_sphere_errors_errors_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Error) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var file_sphere_errors_errors_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         18534200,
		Name:          "sphere.errors.default_status",
		Tag:           "varint,18534200,opt,name=default_status",
		Filename:      "sphere/errors/errors.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*Error)(nil),
		Field:         18534210,
		Name:          "sphere.errors.options",
		Tag:           "bytes,18534210,opt,name=options",
		Filename:      "sphere/errors/errors.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// default_status specifies the fallback HTTP status code for all error values
	// defined within this enum that do not specify their own status.
	// Preconditions: Must be a valid HTTP status code (100-599).
	// Concurrency: Extension descriptors are immutable after registration in init().
	//
	// optional int32 default_status = 18534200;
	E_DefaultStatus = &file_sphere_errors_errors_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// options configures status, reason, and message metadata for this specific enum value.
	// Preconditions: Target Error message must provide valid status/reason/message fields.
	// Concurrency: Extension descriptors are immutable after registration in init().
	//
	// optional sphere.errors.Error options = 18534210;
	E_Options = &file_sphere_errors_errors_proto_extTypes[1]
)

var File_sphere_errors_errors_proto protoreflect.FileDescriptor

const file_sphere_errors_errors_proto_rawDesc = "" +
	"\n" +
	"\x1asphere/errors/errors.proto\x12\rsphere.errors\x1a google/protobuf/descriptor.proto\"Q\n" +
	"\x05Error\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage:F\n" +
	"\x0edefault_status\x12\x1c.google.protobuf.EnumOptions\x18\xb8\x9e\xeb\b \x01(\x05R\rdefaultStatus:T\n" +
	"\aoptions\x12!.google.protobuf.EnumValueOptions\x18\u009e\xeb\b \x01(\v2\x14.sphere.errors.ErrorR\aoptionsB\xa0\x01\n" +
	"\x11com.sphere.errorsB\vErrorsProtoP\x01Z)github.com/go-sphere/errors/sphere/errors\xa2\x02\x03SEX\xaa\x02\rSphere.Errors\xca\x02\rSphere\\Errors\xe2\x02\x19Sphere\\Errors\\GPBMetadata\xea\x02\x0eSphere::Errorsb\x06proto3"

var (
	file_sphere_errors_errors_proto_rawDescOnce sync.Once
	file_sphere_errors_errors_proto_rawDescData []byte
)

func file_sphere_errors_errors_proto_rawDescGZIP() []byte {
	file_sphere_errors_errors_proto_rawDescOnce.Do(func() {
		file_sphere_errors_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sphere_errors_errors_proto_rawDesc), len(file_sphere_errors_errors_proto_rawDesc)))
	})
	return file_sphere_errors_errors_proto_rawDescData
}

var file_sphere_errors_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sphere_errors_errors_proto_goTypes = []any{
	(*Error)(nil),                         // 0: sphere.errors.Error
	(*descriptorpb.EnumOptions)(nil),      // 1: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 2: google.protobuf.EnumValueOptions
}
var file_sphere_errors_errors_proto_depIdxs = []int32{
	1, // 0: sphere.errors.default_status:extendee -> google.protobuf.EnumOptions
	2, // 1: sphere.errors.options:extendee -> google.protobuf.EnumValueOptions
	0, // 2: sphere.errors.options:type_name -> sphere.errors.Error
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sphere_errors_errors_proto_init() }
func file_sphere_errors_errors_proto_init() {
	if File_sphere_errors_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sphere_errors_errors_proto_rawDesc), len(file_sphere_errors_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_sphere_errors_errors_proto_goTypes,
		DependencyIndexes: file_sphere_errors_errors_proto_depIdxs,
		MessageInfos:      file_sphere_errors_errors_proto_msgTypes,
		ExtensionInfos:    file_sphere_errors_errors_proto_extTypes,
	}.Build()
	File_sphere_errors_errors_proto = out.File
	file_sphere_errors_errors_proto_goTypes = nil
	file_sphere_errors_errors_proto_depIdxs = nil
}
