package errors_test

import (
	stderrors "errors"
	"fmt"
	"testing"

	"github.com/go-sphere/errors/sphere/errors"
)

// The interfaces below mirror the ones github.com/go-sphere/httpx classifies
// errors by (httpx/error.go: StatusError, CodeError, MessageError and Error).
// They are redeclared here so this module does not depend on httpx; httpx
// matches them structurally, so conformance to these is conformance to httpx.
type (
	statusError interface {
		error
		GetStatus() int32
	}
	codeError interface {
		error
		GetCode() int32
	}
	messageError interface {
		error
		GetMessage() string
	}
	httpxError interface {
		error
		statusError
		codeError
		messageError
	}
)

func TestNewErrorFields(t *testing.T) {
	cause := stderrors.New("db: connection refused")
	err := errors.NewError(503, 1001, "service unavailable", cause)

	var he httpxError
	if !stderrors.As(err, &he) {
		t.Fatalf("NewError result %T does not implement the httpx Error interface", err)
	}
	if got := he.GetStatus(); got != 503 {
		t.Errorf("GetStatus() = %d, want 503", got)
	}
	if got := he.GetCode(); got != 1001 {
		t.Errorf("GetCode() = %d, want 1001", got)
	}
	if got := he.GetMessage(); got != "service unavailable" {
		t.Errorf("GetMessage() = %q, want %q", got, "service unavailable")
	}
	if got := err.Error(); got != cause.Error() {
		t.Errorf("Error() = %q, want the wrapped error text %q", got, cause.Error())
	}
	if got := stderrors.Unwrap(err); got != cause {
		t.Errorf("Unwrap() = %v, want %v", got, cause)
	}
	if !stderrors.Is(err, cause) {
		t.Error("errors.Is(err, cause) = false, want true")
	}
}

func TestNewErrorNilErrUsesStatusText(t *testing.T) {
	tests := []struct {
		status int32
		want   string
	}{
		{status: 404, want: "Not Found"},
		{status: 500, want: "Internal Server Error"},
		{status: 0, want: "Unknown error"},
		{status: 999, want: "Unknown error"},
	}
	for _, tt := range tests {
		t.Run(fmt.Sprint(tt.status), func(t *testing.T) {
			err := errors.NewError(tt.status, 7, "", nil)
			if got := err.Error(); got != tt.want {
				t.Errorf("Error() = %q, want %q", got, tt.want)
			}
			if stderrors.Unwrap(err) == nil {
				t.Error("Unwrap() = nil, want the default status error")
			}
		})
	}
}

func TestNewErrorKeepsMessageAsGiven(t *testing.T) {
	err := errors.NewError(400, 1, "", stderrors.New("detail"))
	var me messageError
	if !stderrors.As(err, &me) {
		t.Fatal("NewError result does not implement GetMessage")
	}
	if got := me.GetMessage(); got != "" {
		t.Errorf("GetMessage() = %q, want empty (no fallback)", got)
	}
}

func TestNewErrorFoundThroughWrapping(t *testing.T) {
	err := fmt.Errorf("handler: %w", errors.NewError(409, 2002, "email exists", nil))
	var se statusError
	if !stderrors.As(err, &se) || se.GetStatus() != 409 {
		t.Fatalf("errors.As through fmt wrapping failed: %v", err)
	}
	var ce codeError
	if !stderrors.As(err, &ce) || ce.GetCode() != 2002 {
		t.Fatalf("errors.As(CodeError) through fmt wrapping failed: %v", err)
	}
}

// generatedEnumError mimics an enum generated by protoc-gen-sphere-errors.
type generatedEnumError int32

func (e generatedEnumError) Error() string      { return "USER_NOT_FOUND" }
func (e generatedEnumError) GetCode() int32     { return int32(e) }
func (e generatedEnumError) GetStatus() int32   { return 404 }
func (e generatedEnumError) GetMessage() string { return "user not found" }

// TestNewErrorGeneratedJoinShape exercises the exact call shape of the
// generated Join helper.
func TestNewErrorGeneratedJoinShape(t *testing.T) {
	e := generatedEnumError(2001)
	cause := stderrors.New("sql: no rows")
	err := errors.NewError(e.GetStatus(), e.GetCode(), e.GetMessage(), stderrors.Join(e, cause))

	if !stderrors.Is(err, e) || !stderrors.Is(err, cause) {
		t.Fatal("joined error does not match the enum value and the cause")
	}
	var he httpxError
	if !stderrors.As(err, &he) {
		t.Fatal("joined error does not implement the httpx Error interface")
	}
	if he.GetStatus() != 404 || he.GetCode() != 2001 || he.GetMessage() != "user not found" {
		t.Fatalf("got status=%d code=%d message=%q", he.GetStatus(), he.GetCode(), he.GetMessage())
	}
}
